changes to support external development module

diff --git a/trunk/tahoe/makefile.template b/trunk/tahoe/makefile.template
--- a/trunk/tahoe/makefile.template
+++ b/trunk/tahoe/makefile.template
@@ -1,4 +1,4 @@
-# $Id: makefile.template,v 1.16 2003-01-30 00:47:53 paklein Exp $
+# $Id: makefile.template,v 1.17 2003-01-31 10:00:32 paklein Exp $
 # INSTALLATION INSTRUCTIONS
 #
 # (0) copy makefile.template to a local makefile.
@@ -44,22 +44,33 @@ MACRO_DIR = $(HOME_DIR)/../macros
 
 ##### any additional user C, C++, fortran, or linker flags
 #MY_CFLAGS  =
-MY_CCFLAGS = --load-pch $(TB_DIR)/pch
+#MY_CCFLAGS = --load-pch $(TB_DIR)/pch
 #MY_FFLAGS  =
 #MY_LFLAGS  =
 
 ##### toolbox
 TB_DIR      = $(HOME_DIR)/../toolbox
 TB_INC      = -I$(TB_DIR)/inc
-TB_CFLAGS   = $(TB_INC)
+TB_DEFINES  = 
+TB_CFLAGS   = $(TB_INC) $(TB_DEFINES)
 TB_LIB_NAME = toolbox
 TB_LIB      = $(TB_DIR)/lib/lib$(TB_LIB_NAME).a
 TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 
+##### development
+#DEV_DIR      = $(HOME_DIR)/../development
+#DEV_INC      = -I$(DEV_DIR)/inc
+#DEV_DEFINES  = -D__DEVELOPMENT__
+#DEV_CFLAGS   = $(DEV_INC) $(DEV_DEFINES)
+#DEV_LIB_NAME = development
+#DEV_LIB      = $(DEV_DIR)/lib/lib$(DEV_LIB_NAME).a
+#DEV_LFLAGS   = -L$(DEV_DIR)/lib -l$(DEV_LIB_NAME)
+
 ##### F2C 1.4.3
 #F2C_DIR      = $(HOME_DIR)/../../tahoe/f2c
 #F2C_INC      = -I$(F2C_DIR)/inc
-#F2C_CFLAGS   = $(F2C_INC) -D__F2C__
+#F2C_DEFINES  = -D__F2C__
+#F2C_CFLAGS   = $(F2C_INC) $(F2C_DEFINES)
 #F2C_LIB_NAME = f2c_
 #F2C_LIB      = $(F2C_DIR)/lib/lib$(F2C_LIB_NAME).a
 #F2C_LFLAGS   = -L$(F2C_DIR)/lib -l$(F2C_LIB_NAME)
@@ -67,7 +78,8 @@ TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 #### BLAS
 #BLAS_DIR      = $(HOME_DIR)/../CBLAS
 #BLAS_INC      = -I$(BLAS_DIR)/inc
-#BLAS_CFLAGS   = $(BLAS_INC) -D__BLAS__
+#BLAS_DEFINES  = -D__BLAS__
+#BLAS_CFLAGS   = $(BLAS_INC) $(BLAS_DEFINES)
 #BLAS_LIB_NAME = CBLAS
 #BLAS_LIB      = $(BLAS_DIR)/lib/lib$(BLAS_LIB_NAME).a
 #BLAS_LFLAGS   = -L$(BLAS_DIR)/lib -l$(BLAS_LIB_NAME)
@@ -75,7 +87,8 @@ TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 ##### Aztec iterative linear algebra library
 #AZ_DIR      = $(HOME_DIR)/../aztec
 #AZ_INC      = -I$(AZ_DIR)/inc
-#AZ_CFLAGS   = $(AZ_INC) -D__AZTEC__
+#AZ_DEFINES  = -D__AZTEC__
+#AZ_CFLAGS   = $(AZ_INC) $(AZ_DEFINES)
 #AZ_LIB_NAME = aztec
 #AZ_LIB      = $(AZ_DIR)/lib/lib$(AZ_LIB_NAME).a
 #AZ_LFLAGS   = -L$(AZ_DIR)/lib -l$(AZ_LIB_NAME)
@@ -83,7 +96,8 @@ TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 #### SPOOLES
 #SPOOLES_DIR      = $(HOME_DIR)/../spooles
 #SPOOLES_INC      = -I$(SPOOLES_DIR)/inc
-#SPOOLES_CFLAGS   = $(SPOOLES_INC) -D__SPOOLES__
+#SPOOLES_DEFINES  = -D__SPOOLES__
+#SPOOLES_CFLAGS   = $(SPOOLES_INC) $(SPOOLES_DEFINES)
 #SPOOLES_LIB_NAME = spooles
 #SPOOLES_LIB      = $(SPOOLES_DIR)/lib/lib$(SPOOLES_LIB_NAME).a
 #SPOOLES_LFLAGS   = -L$(SPOOLES_DIR)/lib -l$(SPOOLES_LIB_NAME)
@@ -91,7 +105,8 @@ TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 #### SPOOLES MT
 #SPOOLESMT_DIR      = $(HOME_DIR)/../spoolesMT
 #SPOOLESMT_INC      = -I$(SPOOLESMT_DIR)/inc
-#SPOOLESMT_CFLAGS   = $(SPOOLESMT_INC) -D__SPOOLES_MT__
+#SPOOLESMT_DEFINES  = -D__SPOOLES_MT__
+#SPOOLESMT_CFLAGS   = $(SPOOLESMT_INC) $(SPOOLESMT_DEFINES)
 #SPOOLESMT_LIB_NAME = spoolesMT
 #SPOOLESMT_LIB      = $(SPOOLESMT_DIR)/lib/lib$(SPOOLESMT_LIB_NAME).a
 #SPOOLESMT_LFLAGS   = -L$(SPOOLESMT_DIR)/lib -l$(SPOOLESMT_LIB_NAME)
@@ -99,7 +114,8 @@ TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 #### SPOOLES MPI
 #SPOOLESMPI_DIR      = $(HOME_DIR)/../spoolesMPI
 #SPOOLESMPI_INC      = -I$(SPOOLESMPI_DIR)/inc
-#SPOOLESMPI_CFLAGS   = $(SPOOLESMPI_INC) -D__SPOOLES_MPI__
+#SPOOLESMPI_DEFINES  = -D__SPOOLES_MPI__
+#SPOOLESMPI_CFLAGS   = $(SPOOLESMPI_INC) $(SPOOLESMPI_DEFINES)
 #SPOOLESMPI_LIB_NAME = spoolesMPI
 #SPOOLESMPI_LIB      = $(SPOOLESMPI_DIR)/lib/lib$(SPOOLESMPI_LIB_NAME).a
 #SPOOLESMPI_LFLAGS   = -L$(SPOOLESMPI_DIR)/lib -l$(SPOOLESMPI_LIB_NAME)
@@ -107,7 +123,8 @@ TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 #### METIS
 #METIS_DIR      = $(HOME_DIR)/../metis
 #METIS_INC      = -I$(METIS_DIR)/inc
-#METIS_CFLAGS   = $(METIS_INC) -D__METIS__
+#METIS_DEFINES  = -D__METIS__
+#METIS_CFLAGS   = $(METIS_INC) $(METIS_DEFINES)
 #METIS_LIB_NAME = metis
 #METIS_LIB      = $(METIS_DIR)/lib/lib$(METIS_LIB_NAME).a
 #METIS_LFLAGS   = -L$(METIS_DIR)/lib -l$(METIS_LIB_NAME)
@@ -115,23 +132,31 @@ TB_LFLAGS   = -L$(TB_DIR)/lib -l$(TB_LIB_NAME)
 #### ACME
 #ACME_DIR      = $(HOME_DIR)/../libs/acme-0.2a
 #ACME_INC      = -I$(ACME_DIR)/search -I$(ACME_DIR)/enforcement
-#ACME_CFLAGS   = $(ACME_INC) -D__ACME__
+#ACME_DEFINES  = -D__ACME__
+#ACME_CFLAGS   = $(ACME_INC) $(ACME_DEFINES)
 #ACME_LIB_NAME = acme
 #ACME_LIB      = $(ACME_DIR)/lib$(ACME_LIB_NAME).a
 #ACME_LFLAGS   = -L$(ACME_DIR) -l$(ACME_LIB_NAME)
 
 ##### SEACAS/ACCESS software
-#AX_INC    = -I$(ACCESS)/inc
-#AX_CFLAGS = $(AX_INC) -D__ACCESS__
-#AX_LFLAGS = -L$(ACCESS)/lib -lexoIIv2c -lnetcdf
+#AX_INC     = -I$(ACCESS)/inc
+#AX_DEFINES = -D__ACCESS__
+#AX_CFLAGS  = $(AX_INC) $(AX_DEFINES)
+#AX_LFLAGS  = -L$(ACCESS)/lib -lexoIIv2c -lnetcdf
 
 #### NOX nonlinear solver
 #NOX_DIR      = $(HOME_DIR)/../nox
 #NOX_INC      = -I$(NOX_DIR)/include -I$(NOX_DIR)/include/nox
-#NOX_CFLAGS   = $(NOX_INC) -D__NOX__
+#NOX_DEFINES  = -D__NOX__
+#NOX_CFLAGS   = $(NOX_INC) $(NOX_DEFINES)
 #NOX_LIB_NAME = nox
 #NOX_LIB      = $(NOX_DIR)/lib/lib$(NOX_LIB_NAME).a
 #NOX_LFLAGS   = -L$(NOX_DIR)/lib -l$(NOX_LIB_NAME)
+
+##### keeping optional modules up to date
+UP_TO_DATE = NONE
+#UP_TO_DATE = $(DEV_DIR)
+
 ############################### build options ###########################
 
 # extra macros for specific modules
@@ -143,9 +168,11 @@ include $(MACRO_DIR)/tahoe.extras
 # below to the associated make_[]extras target.
 # This two part approach is for backward compatibility between make.targets
 # and older versions of makefile.template
-MAKE_INIT_XTRAS  = update_config
-#MAKE_BUILD_XTRAS = make_build_extras
-MAKE_CLEAN_XTRAS = clean_config
+MAKE_INIT_XTRAS        = update_config
+MAKE_HEADERS_XTRAS     = make_headers_extras
+MAKE_DEPEND_INIT_XTRAS = make_depend_init_extras
+MAKE_BUILD_XTRAS       = make_build_extras
+MAKE_CLEAN_XTRAS       = clean_config
 
 # include common target definitions
 include $(MACRO_DIR)/make.targets
@@ -153,14 +180,24 @@ include $(MACRO_DIR)/make.targets
 # init extras target
 update_config:
 	@ if test -f $(SRC_DIR)/config/SolidMaterialsConfig.make; then rm $(SRC_DIR)/config/SolidMaterialsConfig.make; fi
-	@ if test -f $(SRC_DIR)/config/ElementsConfig.make;  then rm $(SRC_DIR)/config/ElementsConfig.make;  fi
+	@ if test -f $(SRC_DIR)/config/ElementsConfig.make; then rm $(SRC_DIR)/config/ElementsConfig.make;  fi
 	@ cd config; $(PERL) $(MACRO_DIR)/MakeConfigHeaderFile.pl SolidMaterialsConfig.conf $(SRC_DIR)/config
 	@ cd config; $(PERL) $(MACRO_DIR)/MakeConfigHeaderFile.pl ElementsConfig.conf  $(SRC_DIR)/config
 	@ cd config; $(PERL) $(MACRO_DIR)/MakeConfigMakeFile.pl   SolidMaterialsConfig.conf $(SRC_DIR)/config
 	@ cd config; $(PERL) $(MACRO_DIR)/MakeConfigMakeFile.pl   ElementsConfig.conf  $(SRC_DIR)/config
+	@ make do_up_to_date "COMMAND = update_config"
+
+# create symbolic links
+make_headers_extras:
+	@ make do_up_to_date "COMMAND = headers"
+
+# update file dependencies
+make_depend_init_extras:
+	@ make do_up_to_date "COMMAND = depend_init object_list"
 
 # build extras target
 make_build_extras:
+	@ make do_up_to_date "COMMAND = build"
 
 # clean extras target - clean config files out of src/config
 clean_config:
@@ -168,3 +205,21 @@ clean_config:
 	@ if test -f $(SRC_DIR)/config/SolidMaterialsConfig.make; then rm $(SRC_DIR)/config/SolidMaterialsConfig.make; fi
 	@ if test -f $(SRC_DIR)/config/ElementsConfig.h; then rm $(SRC_DIR)/config/ElementsConfig.h; fi
 	@ if test -f $(SRC_DIR)/config/ElementsConfig.make; then rm $(SRC_DIR)/config/ElementsConfig.make; fi
+	@ if test -f $(SRC_DIR)/config/DevelopmentElementsConfig.h; then rm $(SRC_DIR)/config/DevelopmentElementsConfig.h; fi
+	@ if test -f $(SRC_DIR)/config/DevelopmentElementsConfig.make; then rm $(SRC_DIR)/config/DevelopmentElementsConfig.make; fi
+	@ if test -f $(SRC_DIR)/config/DevelopmentMaterialsConfig.h; then rm $(SRC_DIR)/config/DevelopmentMaterialsConfig.h; fi
+	@ if test -f $(SRC_DIR)/config/DevelopmentMaterialsConfig.make; then rm $(SRC_DIR)/config/DevelopmentMaterialsConfig.make; fi
+	@ if test -L $(SRC_DIR)/$(DEV_NAME); then rm $(SRC_DIR)/$(DEV_NAME); fi
+
+# loop over up-to-date list - must define $(COMMAND)
+do_up_to_date:
+	@ for module in $(UP_TO_DATE); do \
+		if test -d $$module; then \
+			cd $$module; $(MAKE) $(COMMAND) || exit 1; \
+		else \
+			if test $$module != "NONE"; then \
+				$(ECHO) "\n*** module not found: $$module"; \
+				exit 1; \
+			fi; \
+		fi; \
+	done	
